# Generated by Django 6.0.5 on 2026-05-11 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Agua', 'Agua'), ('Fuego', 'Fuego'), ('Planta', 'Planta'), ('Eléctrico', 'Eléctrico'), ('Tierra', 'Tierra')], max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagen', models.URLField()),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.entrenador')),
            ],
        ),
    ]
