# Generated by Django 6.0.5 on 2026-05-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='apellido',
            field=models.CharField(default='SinApellido', max_length=50),
            preserve_default=False,
        ),
    ]
