# Generated by Django 6.0.5 on 2026-05-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_entrenador_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='imagen',
            field=models.URLField(default='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/trainers/ash.png'),
            preserve_default=False,
        ),
    ]
