# Generated by Django 6.0.5 on 2026-05-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_entrenador_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
