# Generated by Django 6.0.5 on 2026-05-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_entrenador_video_pokemon_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='tipo',
            field=models.CharField(choices=[('A', 'Agua'), ('F', 'Fuego'), ('P', 'Planta'), ('E', 'Eléctrico'), ('T', 'Tierra')], max_length=20),
        ),
    ]
